name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./apps/server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/easypoker-api:${{ github.event.pull_request.number }}
#        tags: ${{ secrets.DOCKERHUB_USERNAME }}/easypoker-api:$(date +%s)
